name: Build and Push Podman Image to GitHub Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Log in to GitHub Container Registry
        env:
          CR_PAT: ${{ secrets.PODMAN }}
        run: |
          echo $CR_PAT | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Podman Image
        run: |
          podman build -t ghcr.io/${{ github.repository_owner }}/openvpn-socks:latest .

      - name: Push Image to GitHub Packages
        run: |
          podman push ghcr.io/${{ github.repository_owner }}/openvpn-socks:latest
